### ISSUE TITLE
Server crashes when transcoder is not found

### ISSUE THREAD

**Issue by Raman236** [Arthi-chaud/Meelo#938]
Hi

I should have brought this up a while back.

When I build/run the docker compose, it builds most of the containers, but then gets stuck at building the music Server, and exits or doesnt build because the server container is unhealthy.

After a minute or two, the server becomes green, and then when I build the instance again, it builds successfully. Any idea why? and how to resolve that issue?

I have tried, coolify and portainer and both do the same thing.
Here are some of the screenshots

![Image](https://github.com/user-attachments/assets/382758a3-70f6-4b89-9bc2-080773e38951)
![Image](https://github.com/user-attachments/assets/53d1e682-a88b-422c-a51a-83fdf3c98046)
![Image](https://github.com/user-attachments/assets/b25f2113-ce39-4af1-ac49-dbf90017282b)
![Image](https://github.com/user-attachments/assets/1be09f2b-f984-4faf-a5bc-2ce00238bb0e)

When it goes green, I build the container again and then it builds successfully
![Image](https://github.com/user-attachments/assets/59932945-12e4-407c-9dfd-7fe295ad1120)
![Image](https://github.com/user-attachments/assets/ef2e6ffc-3028-4653-ba74-425248efda1b)

My docker compose file:
```
# This compose allows to setup the whole project in the production environment 
services:
  server:
    image: ghcr.io/arthi-chaud/meelo-server:latest
    expose:
      - 4000
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
      mq:
        condition: service_healthy
    volumes:
      - ${DATA_DIR}:${INTERNAL_DATA_DIR}
      - ${CONFIG_DIR}:${INTERNAL_CONFIG_DIR}
    env_file:
      - .env
    environment:
      - TRANSCODER_URL=http://transcoder:7666
      - MEILI_HOST=http://meilisearch:7700
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@mq:5672
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- localhost:4000"]
      interval: 5s
      timeout: 5s
      retries: 5
  scanner:
    image: ghcr.io/arthi-chaud/meelo-scanner:latest
    expose:
      - 8133
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- localhost:8133"]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - API_URL=http://server:4000
      - INTERNAL_CONFIG_DIR=${INTERNAL_CONFIG_DIR}
      - INTERNAL_DATA_DIR=${INTERNAL_DATA_DIR}
      - API_KEYS=${API_KEYS}
    volumes:
      - ${DATA_DIR}:${INTERNAL_DATA_DIR}:ro
      - ${CONFIG_DIR}:${INTERNAL_CONFIG_DIR}:ro
  front:
    image: ghcr.io/arthi-chaud/meelo-front:latest
    expose:
      - 3000
    depends_on:
      server:
        condition: service_healthy
      scanner:
        condition: service_healthy
    environment:
      - PUBLIC_SERVER_URL=${PUBLIC_URL}/api
      - SSR_SERVER_URL=http://server:4000
      - PUBLIC_SCANNER_URL=${PUBLIC_URL}/scanner
      - SSR_SCANNER_URL=http://scanner:8133
  matcher:
    image: ghcr.io/arthi-chaud/meelo-matcher:latest
    restart: on-failure
    depends_on:
      server:
        condition: service_healthy
      mq:
        condition: service_healthy
    environment:
      - API_URL=http://server:4000
      - INTERNAL_CONFIG_DIR=${INTERNAL_CONFIG_DIR}
      - API_KEYS=${API_KEYS}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@mq:5672
    volumes:
      - ${CONFIG_DIR}:${INTERNAL_CONFIG_DIR}:ro
  db:
    image: postgres:alpine3.14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v1.5
    restart: on-failure
    expose:
      - 7700
    volumes:
      - ./search:/meili_data
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_LOG_LEVEL=WARN
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://0.0.0.0:7700/health"]
      timeout: 5s
      retries: 5
  transcoder:
    image: ghcr.io/zoriya/kyoo_transcoder:master
    restart: on-failure
    cpus: 1
    expose:
      - 7666
    environment:
      - GOCODER_SAFE_PATH=${INTERNAL_DATA_DIR}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SCHEMA=gocoder
      - POSTGRES_SERVER=db
    volumes:
      - ${DATA_DIR}:${INTERNAL_DATA_DIR}:ro
      - ./transcoder_cache:/cache
    depends_on:
      db:
        condition: service_healthy
    profiles: ['', 'cpu']
  mq:
    image: rabbitmq:4.0-alpine
    environment:
      - RABBITMQ_NODENAME=meelo
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
  nginx:
    restart: on-failure
    image: nginx:1.24.0-alpine
    depends_on:
      server:
        condition: service_started
      front:
        condition: service_started
    ports:
      - ${PORT:-5000}:5000
    environment:
      - PORT=5000
      - FRONT_URL=http://front:3000
      - SERVER_URL=http://server:4000
      - SCANNER_URL=http://scanner:8133
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/meelo.conf.template:ro
#volumes:
#  db:
#  config:
#  data:
#  search:
#  transcoder_cache:
#  rabbitmq_data:

```
